#firstName-- CHRISTINA ROSS
-- MySQL Script generated by MySQL Workbench
-- Wed Oct 16 18:08:45 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineeringgeneral_ledger_accounts

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema myTiPJar
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `myTiPJar` ;

-- -----------------------------------------------------
-- Schema myTiPJar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myTiPJar` DEFAULT CHARACTER SET utf8 ;
USE `myTiPJar` ;

-- -----------------------------------------------------
-- Table `myTiPJar`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myTiPJar`.`user` ;

CREATE TABLE IF NOT EXISTS `myTiPJar`.`user` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `idUser_UNIQUE` (`userId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myTiPJar`.`shift`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myTiPJar`.`shift` ;

CREATE TABLE IF NOT EXISTS `myTiPJar`.`shift` (
  `shiftId` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `totalDuration` DECIMAL(10,2) NOT NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`shiftId`),
  INDEX `userId_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_user_shift`
    FOREIGN KEY (`userId`)
    REFERENCES `myTiPJar`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myTiPJar`.`tip_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myTiPJar`.`tip_record` ;

CREATE TABLE IF NOT EXISTS `myTiPJar`.`tip_record` (
  `tipID` INT NOT NULL AUTO_INCREMENT,
  `shiftId` INT NOT NULL,
  `cashTip` DECIMAL(10,2) NOT NULL,
  `cardTip` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`tipID`),
  INDEX `shiftID_idx` (`shiftId` ASC) VISIBLE,
  CONSTRAINT `fk_shift_tip`
    FOREIGN KEY (`shiftId`)
    REFERENCES `myTiPJar`.`shift` (`shiftId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myTiPJar`.`Analytics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myTiPJar`.`Analytics` ;

CREATE TABLE IF NOT EXISTS `myTiPJar`.`Analytics` (
  `analyticsId` INT NOT NULL AUTO_INCREMENT,
  `avgTipsPerHr` DECIMAL(10,2) NOT NULL,
  `shiftId` INT NOT NULL,
  `totalTips` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`analyticsId`),
  INDEX `shiftId_idx` (`shiftId` ASC) VISIBLE,
  CONSTRAINT `fk_shift_analytics`
    FOREIGN KEY (`shiftId`)
    REFERENCES `myTiPJar`.`shift` (`shiftId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myTiPJar`.`tax_calculation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myTiPJar`.`tax_calculation` ;

CREATE TABLE IF NOT EXISTS `myTiPJar`.`tax_calculation` (
  `taxId` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `year` VARCHAR(45) NOT NULL,
  `calculatedTax` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`taxId`),
  INDEX `userId_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_user_tax`
    FOREIGN KEY (`userId`)
    REFERENCES `myTiPJar`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myTiPJar`.`predictions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myTiPJar`.`predictions` ;

CREATE TABLE IF NOT EXISTS `myTiPJar`.`predictions` (
  `predictionsId` INT NOT NULL AUTO_INCREMENT,
  `userID` INT NOT NULL,
  `bestDay` VARCHAR(45) NULL,
  `predictCal` DECIMAL(10,2) NULL,
  PRIMARY KEY (`predictionsId`),
  INDEX `userId_idx` (`userID` ASC) VISIBLE,
  CONSTRAINT `fk_user_predictions`
    FOREIGN KEY (`userID`)
    REFERENCES `myTiPJar`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myTiPJar`.`earnings_report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myTiPJar`.`earnings_report` ;

CREATE TABLE IF NOT EXISTS `myTiPJar`.`earnings_report` (
  `reportId` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `startDate` DATETIME NOT NULL,
  `endDate` DATETIME NOT NULL,
  `totalTips` DECIMAL(10,2) NOT NULL,
  `totalHours` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`reportId`),
  INDEX `userId_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_user_report`
    FOREIGN KEY (`userId`)
    REFERENCES `myTiPJar`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
